### PR TITLE
Updated NuGet Packages to latest version. May fix some Bugs

### PR DESCRIPTION
**Pull request by mohamedsakeel**
Closes #ISSUE_NUMBER

### CODE REVIEW

**Comment by derech1e** [comment]
Which bugs should that fixes?

**Comment by mohamedsakeel** [comment]
> Which bugs should that fixes?

I am not sure I was trying to add the Download speed and the size of the file to the SingleDownload and MultipleDownload and just looked the NuGet packages for updates and found major updates.

**Comment by Tyrrrz** [comment]
Thanks, but it doesn't fix any bugs and MaterialDesign libraries are kept at lower versions on purpose.

**Comment by mohamedsakeel** [comment]
> Thanks, but it doesn't fix any bugs and MaterialDesign libraries are kept at lower versions on purpose.

Oh then alright

**Pull request closed without merging**
