### PR TITLE
Skip download if file exists

### LINKED ISSUE #69: Must detect already downloaded file
It must detect already downloaded file in downloaded location and if file exist then just show finish.
While downloading playlists many time same video is added in different playlist and currently it gets downloaded multiple times.

### PR DESCRIPTION
**Pull request by mostafa901**
Hi, Thanks for  this great app.
I have add an option to skip downloading Existing File.
Basically a checkbox to skip Downloading existing
if(unchecked)
the normal behaviour will occur => create a unique file name

if(checked and file exists)
Downloadfilemodel is added to the list and it will show as done 

Closes #69

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Hi, thanks for your PR.
It looks like your IDE is replacing spaces with tabs so the diff viewer is freaking out and showing the entire files as changed. Could you revert the space changes please?

**Comment by mostafa901** [comment]
sure will do now... I will disable the auto formatter.

**Comment by mostafa901** [comment]
I have removed them, but I keep seeing multiple white lines on Git, do you prefer cancel this PR and submit a new PR?

**Comment by Tyrrrz** [comment]
That's unfortunate but let's stick with it.

I scanned the files anyway and it seems you're passing `SkipExisting` to both `DownloadViewModel` and `DialogScreen`. I think it only needs to be on `DownloadMultipleSetupViewModel`, if it's set we can just skip creating a `DownloadViewModel` altogether.

**Comment by mostafa901** [comment]
Well, i did that at first, but i felt it is not comfortable for user experience. Users need to see what are downloaded vs what not yet. But your point is valid as well

**Comment by Tyrrrz** [comment]
I see your point but isn't it misleading if the download appears as downloaded when in fact there was no download happening because the file was already there?

**Comment by mostafa901** [comment]
Well you can think of it as if user is continuing download... but may be we
can change the word "Done" to "skipped"?

**Comment by Tyrrrz** [comment]
I'm still leaning more towards not including them at all.

**Comment by mostafa901** [comment]
Ok...I will update the code tomorrow.

**Comment by Tyrrrz** [comment]
Merged, thanks

**Pull request merged**
