### PR TITLE
Update YoutubeExplode to latest version

### LINKED ISSUE #156: JsonReaderException: 'a' is an invalid start of a property name
when we try to extract the video https://www.youtube.com/watch?v=Q7QDDBRwwNg&t=6s, we got the following error:
Capture

### PR DESCRIPTION
**Pull request by cuno92**
Fix #156

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Thanks!

**Comment by xknat** [comment]
Awsome! This is why i love github community

**Comment by RomeoDavide91** [comment]
Great! Now work!

**Comment by ShareASmile** [comment]
That's great! Thank You

**Pull request merged**
