### PR TITLE
Added Bulk-Search with multiple search terms splitted by ';' ...

### PR DESCRIPTION
**Pull request by qwe1qwe**
Added Bulk-Search with multiple search terms splitted by ';' and get the first result from youtube.

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Hi, thanks for the PR.
Why is it only getting the first video from each search result?

**Comment by qwe1qwe** [comment]
Hi, 
some people, like me, have some links and just want to download the first video / song. Mostly the first video is the right one.
You can change the code as you wish.

**Comment by Tyrrrz** [comment]
Fair enough. I'll take a look when I have time.

**Comment by Tyrrrz** [comment]
I implemented it slightly different in https://github.com/Tyrrrz/YoutubeDownloader/commit/d83d7355aece3395804baf2fb97ca80674e29b88

**Pull request closed without merging**
