### PR TITLE
Support for proxy

### PR DESCRIPTION
**Pull request by maikebing**

### CODE REVIEW

**Comment by maikebing** [comment]
Hi, Tyrrrz , Do you have time to review the code? Is there anything that needs to be changed?

**Comment by Tyrrrz** [comment]
Hi @maikebing. Frankly, I doubt I will have the time any time soon.

My initial instinct would be to push towards system proxy settings instead, which would affect all applications running on the computer:

image

**Comment by maikebing** [comment]
Some websites are not directly accessible in some areas and need to go through a proxy, but other software does not, so I don't want to set up a proxy server in the operating system. So, I still hope you consider merging PRs.

**Comment by Tyrrrz** [comment]
I understand the use case, but I don't think it will be worth maintaining an additional option in the application, for what's essentially a cross-cutting concern.

Note that you can also configure proxy on a per-application basis, using environment variables. You could create a batch or a powershell script to achieve this.

Here are some docs on that topic: https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy?view=net-7.0#remarks

image

If that doesn't solve your issue, I would suggest that you continue using your own fork instead. I don't want to include this upstream though.

**Comment by mrmashal** [comment]
It took me a while to figure out what exactly I should put into my script to make it work with a SOCKS5 proxy listening on port 1080 on the local machine. Here it is as a sample for future reference:

Windows (batch script):
```
SET ALL_PROXY=socks5://127.0.0.1:1080
YoutubeDownloader.exe
```

Linux (bash script):
```
#!/bin/bash
export ALL_PROXY="socks5://127.0.0.1:1080"
./YoutubeDownloader
```

**Pull request closed without merging**
