### PR TITLE
Fix snackbar colors in dark mode

### PR DESCRIPTION
**Pull request by derech1e**
A suggested solution for the new Snackbar theme.

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Can you show the screenshot of what it looks like after the change?

**Comment by derech1e** [comment]
> Can you show the screenshot of what it looks like after the change?

Screen_1
Screen_2
Screen_3
Screen_4

**Comment by Tyrrrz** [comment]
Hmm, it seems to look exactly the same as it does now, doesn't it?
image

**Comment by derech1e** [comment]
> Hmm, it seems to look exactly the same as it does now, doesn't it?
> image

Not exactly. Currently the contrast between the button and the background is terrible:

image

**Comment by Tyrrrz** [comment]
Oh, it's on dark mode that it changed. Understood.
Thanks!

**Pull request merged**
